<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            [
                'title'         => 'Akvárium Klub',
                'description'   => 'Budapest egyik leghíresebb koncert- és klubhelyszíne az Erzsébet téren. Három terem, három különböző hangulat - mainstream slágertől az underground technoig. Minden pénteken élő koncertek, utána DJ szettek hajnalig. Lenyűgöző vizuális show, professzionális hangrendszer. A város szívében, könnyen megközelíthető. Korhatár: 18+',
                'rating'        => 4.1,
                'date'          => '2026-07-10',
                'time'          => '22:00:00',
                'location'      => 'Budapest, Akvárium Klub, Erzsébet tér 12.',
                'image_url'     => 'https://akvariumklub.hu/wp-content/uploads/2020/08/1400-932-max-3.jpg',
                'category'      => 'Klub',
                'organizer'     => 'Akvárium Klub',
                'tags'          => 'Electro,House,Techno',
                'price'         => '3000-4000 Ft',
                'contact_phone' => '+36 30 860 3368',
            ],
            [
                'title'         => 'Ötkert',
                'description'   => 'Népszerű klub a Gozsdu udvar szívében, több teremmel és változatos zenékkel. Táncdalok, house, pop és elektronikus slágerek. Kiváló helyszín baráti bulizásra, közel a legjobb éttermekhez és bárokhoz. Nagy tánctér, koktélbár minden szinten. Happy hour 22-24 óráig!',
                'rating'        => 4.5,
                'date'          => '2026-07-11',
                'time'          => '21:00:00',
                'location'      => 'Budapest, Ötkert, Zrínyi utca 4/a',
                'image_url'     => 'https://otkert.hu/wp-content/uploads/2022/05/otkert-kisokos.jpg',
                'category'      => 'Klub',
                'organizer'     => 'Ötkert',
                'tags'          => 'Pop,House,Dance',
                'price'         => '2000-2500 Ft',
                'contact_phone' => '+36 70 330 8652',
            ],
            [
                'title'         => 'Heaven Club',
                'description'   => 'Modern klub a legújabb EDM és pop slágerekel. LED falak, UV effektek, és Instagram-worthy fotópontok minden sarkon. Nemzetközi DJ vendégek, bottle service VIP részleg. Dress code: elegáns/casual. Fiatal, energikus közönség. Pezsgőakció éjfélkor!',
                'rating'        => 4.7,
                'date'          => '2026-07-15',
                'time'          => '23:00:00',
                'location'      => 'Budapest, Heaven Club, Deák Ferenc utca 5.',
                'image_url'     => 'https://cdn.sanity.io/images/gfykh5ro/production/a1c2ad89692a064c355752de6e042ae4d6ebcae2-5748x3832.jpg?w=1920&h=1080&q=80&auto=format',
                'category'      => 'Klub',
                'organizer'     => 'Heaven Club',
                'tags'          => 'EDM,Pop,Commercial',
                'price'         => '2500-3500 Ft',
                'contact_phone' => '+36 30 151 2000',
            ],
            [
                'title'         => "Morrison's 2",
                'description'   => "6 terem, 6 különböző zenei stílus! Latino, R&B, Hip-Hop, táncdalok és még sok más. Budapest egyik legismertebb és legnépszerűbb klubja. Hatalmas tánctér, profi fényshow. Ital akciók éjfélig. Születésnaposoknak ingyenes belépés! Minden pénteken és szombaton telt ház.",
                'rating'        => 4.4,
                'date'          => '2026-07-17',
                'time'          => '22:00:00',
                'location'      => "Budapest, Morrison's 2, Szent István körút 11.",
                'image_url'     => 'https://morrisons2.hu/wp-content/uploads/2024/02/udvar-5.jpg',
                'category'      => 'Klub',
                'organizer'     => "Morrison's",
                'tags'          => 'Pop,Latino,R&B,Hip-Hop',
                'price'         => '2000-2500 Ft',
                'contact_phone' => '+36 1 374 3329',
            ],
            [
                'title'         => 'Instant-Fogas Komplexum',
                'description'   => 'Legendás romkocsma-klub komplexum 26 különböző teremmel! Techno, alternatív, indie, pop - mindent megtalálsz. Egyedi atmoszféra, művészi dekoráció, labirintusszerű helyiségek. Fedett és fedetlen részek. Nyáron a kert is nyitva. Ez Budapest egyik legikonikusabb éjszakai helyszíne!',
                'rating'        => 4.3,
                'date'          => '2026-07-18',
                'time'          => '21:00:00',
                'location'      => 'Budapest, Instant-Fogas, Akácfa utca 51.',
                'image_url'     => 'https://kep.cdn.index.hu/1/0/5559/55598/555986/55598689_4109401_0d07d362dc1ca573eb9caeaedd436955_wm.jpg',
                'category'      => 'Klub',
                'organizer'     => 'Instant-Fogas',
                'tags'          => 'Techno,Alternative,Pop',
                'price'         => '1500-2500 Ft',
                'contact_phone' => '+36 70 638 5040',
            ],
            [
                'title'         => 'Lärm',
                'description'   => 'Hardcore underground techno rave! Minimális dekoráció, maximális zene. Stroboszkóp, füstgép, és a város legjobb sound systemje. Csak a legelszántabbaknak! Nemzetközi DJ-k, minimal és hard techno. Teljesen elmerülhetsz a zenében. Korhatár: 21+',
                'rating'        => 3.7,
                'date'          => '2026-07-22',
                'time'          => '23:30:00',
                'location'      => 'Budapest, Lärm, Akácfa utca 51.',
                'image_url'     => 'https://res.cloudinary.com/electronic-beats/c_fit,q_auto,f_auto,w_1920/stage/uploads/sites/8/2019/06/larm_fekvo.jpg',
                'category'      => 'Rave',
                'organizer'     => 'Lärm',
                'tags'          => 'Techno,Underground,Rave',
                'price'         => '2000-3000 Ft',
                'contact_phone' => '+36 30 537 2695',
            ],
            [
                'title'         => 'Aether club',
                'description'   => 'Minimal és melodic techno a legprofibb hangrendszeren. Meghitt atmoszféra, minőségi közönség, aki a zenéért jön. Lézershowk, vizuális projekciók. Chill-out zóna a pihenéshez. A budapesti techno szcéna egyik legfontosabb helyszíne. Resident és vendég DJ-k.',
                'rating'        => 4.2,
                'date'          => '2026-07-24',
                'time'          => '23:00:00',
                'location'      => 'Budapest, Aether Club, Veres Pálné utca 33/a.',
                'image_url'     => 'https://static.ra.co/images/clubs/lg/aethercrowd1.jpg?dateUpdated=1662639935553',
                'category'      => 'Klub',
                'organizer'     => 'Aether',
                'tags'          => 'Minimal,Techno,Melodic',
                'price'         => '2500-3000 Ft',
                'contact_phone' => '+36 70 229 5127',
            ],
            [
                'title'         => 'Szimpla Kert',
                'description'   => 'Budapest leghíresebb romkocsmája! Egyedi dizájn, minden sarok más hangulatú. Akusztikus koncert a kertben, utána DJ szettek. Craft sörök, különleges borok. Tökéletes hely barátokkal találkozni. Turisták és helyiek kedvence. A koncert után nyitva hajnal 2-ig.',
                'rating'        => 4.6,
                'date'          => '2026-07-12',
                'time'          => '20:00:00',
                'location'      => 'Budapest, Szimpla Kert, Kazinczy utca 14.',
                'image_url'     => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/62/0d/95/szimpla-kert.jpg?w=1200&h=1200&s=1',
                'category'      => 'Chill',
                'organizer'     => 'Szimpla Kert',
                'tags'          => 'Acoustic,Live,Chill',
                'price'         => '2000-6000 Ft',
                'contact_phone' => '+36 20 261 8669',
            ],
            [
                'title'         => 'Kőleves Vendéglő és Kert',
                'description'   => 'Laza, barátságos romkocsma különleges ételekkel és italokkal. Nyári hangulat télen is - fűtött kert! Élő zene csütörtökönként, DJ szettek hétvégén. Craft koktélok, helyi sörök. Barátságos személyzet, kiváló árak. Társasjátékok, közösségi asztalok.',
                'rating'        => 4.6,
                'date'          => '2026-07-14',
                'time'          => '19:00:00',
                'location'      => 'Budapest, Kőleves Kert, Kazinczy utca 37-41',
                'image_url'     => 'https://kep.cdn.index.hu/1/0/6083/60839/608399/60839913_4499677_efa2ddd95b5e3e0eb113a280f9516491_wm.jpg',
                'category'      => 'Chill',
                'organizer'     => 'Kőleves',
                'tags'          => 'Chill,Live,Alternative',
                'price'         => '2000-4000 Ft',
                'contact_phone' => '+36 20 213 5999',
            ],
            [
                'title'         => 'Dürer Kert',
                'description'   => 'Koncertek, alter, rock és elektronikus zene. Fedett és fűtött kert télen is. Roller disco pálya, büfé street food-dal. Punk, rock, indie koncertek. Fiatal, alternatív közönség. Craft sörök és pálinkaválaszték. A budapesti underground kultúra központja.',
                'rating'        => 4.5,
                'date'          => '2026-07-19',
                'time'          => '21:00:00',
                'location'      => 'Budapest, Dürer Kert, Öböl utca 1.',
                'image_url'     => 'https://kep.cdn.indexvas.hu/1/0/6416/64163/641634/64163469_d0cf4ce9ebf31a8ee78043f29b0ff767_wm.jpg',
                'category'      => 'Klub',
                'organizer'     => 'Dürer Kert',
                'tags'          => 'Rock,Indie,Alternative',
                'price'         => '1500-2500 Ft',
                'contact_phone' => '+36 1 209 3269',
            ],
            [
                'title'         => 'Kopaszi Kert',
                'description'   => 'Baráti összejövetelek a Duna-parton! Piknik hangulat, sunset DJ szett. Hozd a takaródat és a barátaidat. Food truckók, craft sörök. Kerékpáros közönség. Nyugodt, kikapcsolódó hangulat. Gyönyörű kilátás a természetre. Kutyabarát helyszín.',
                'rating'        => 4.1,
                'date'          => '2026-07-16',
                'time'          => '17:00:00',
                'location'      => 'Budapest, Kopaszi-gát 6-8',
                'image_url'     => 'https://picsum.photos/800/600?random=15',
                'category'      => 'Chill',
                'organizer'     => 'Kopaszi-gát',
                'tags'          => 'Chill,Sunset,Nature',
                'price'         => '2000-4000 Ft',
                'contact_phone' => '+36 30 441 7414',
            ],
            [
                'title'         => 'Pontoon',
                'description'   => 'Duna-parti hajóbuli! Naplemente, panoráma a Parlamentre. Chill house és lounge zene. Koktélbár, fingerfood menü. Romantikus hangulat, tökéletes randihelyszín. Fedett terasz, fűtés télen is. Fotózásra ideális! DJ szettek hétvégén.',
                'rating'        => 4.2,
                'date'          => '2026-07-23',
                'time'          => '19:00:00',
                'location'      => 'Budapest, Id. Antall József rkp. 1',
                'image_url'     => 'https://picsum.photos/800/600?random=16',
                'category'      => 'Egyéb',
                'organizer'     => 'Pontoon',
                'tags'          => 'Lounge,Sunset,Chill',
                'price'         => '2000-6000 Ft',
                'contact_phone' => '+36 30 977 3368',
            ],
            [
                'title'         => '360 Bar',
                'description'   => 'Panorámás tetőbár a város legjobb kilátásával! Lenyűgöző 360 fokos panoráma Budapestre. Koktélbár, DJ szettek, elegáns közönség. Dress code: smart casual. Asztalfoglalás ajánlott. Prémium italok, fingerfood menü. Instagram heaven!',
                'rating'        => 4.2,
                'date'          => '2026-07-27',
                'time'          => '20:00:00',
                'location'      => 'Budapest, Andrássy út 39',
                'image_url'     => 'https://www.360bar.hu/wp-content/uploads/2020/05/b-139-web.jpg',
                'category'      => 'Chill',
                'organizer'     => '360 Bar',
                'tags'          => 'Rooftop,Lounge,Panorama',
                'price'         => '3000 Ft',
                'contact_phone' => '+36 30 360 3600',
            ],
            [
                'title'         => 'A38 Hajó',
                'description'   => 'Kultikus koncerthajó a Dunán! Jazz koncert nemzetközi művészekkel. Étterem a fedélzeten, vacsorával kombinált jegyek. Páratlan dunai panoráma. A koncert után DJ szett. Különleges atmoszféra a vízen. Budapest egyik legikonikusabb helyszíne.',
                'rating'        => 4.5,
                'date'          => '2026-07-29',
                'time'          => '20:30:00',
                'location'      => 'Budapest, Petőfi híd déli oldal',
                'image_url'     => 'https://www.a38.hu/themes/a38/assets/images/frontend/postbanner.jpg',
                'category'      => 'Egyéb',
                'organizer'     => 'A38',
                'tags'          => 'Jazz,Live,Concert',
                'price'         => '3500-6000 Ft',
                'contact_phone' => '+36 1 464 3940',
            ],
            [
                'title'         => 'Sziget Fesztivál 2026',
                'description'   => 'Európa egyik legnagyobb zenei fesztiválja! 7 nap, több mint 1000 koncert és program. Nemzetközi és hazai sztárok. Sziget a Dunán, felejthetetlen élmény. Kempingezés, street food, művészet. Minden zenei stílus. Nem csak koncert, hanem életérzés!',
                'rating'        => 4.3,
                'date'          => '2026-12-10',
                'time'          => '14:00:00',
                'location'      => 'Budapest, Hajógyári-sziget',
                'image_url'     => 'https://turizmus.com/userfiles/myResource/articles/20250812/Sziget-fesztival-koncert.jpg',
                'category'      => 'Fesztivál',
                'organizer'     => 'Sziget Kft.',
                'tags'          => 'Festival,Music,International',
                'price'         => '99500 Ft (bérlet)',
                'contact_phone' => '+36 1 372 0650',
            ],
            [
                'title'         => 'Budapest Park',
                'description'   => 'Szabadtéri koncertek és bulik a Városligetben! Hazai és nemzetközi sztárok. Nagy színpad, profi technika. Food court, italstandok. Nyári esték Budapesten. Családbarát és bulizós programok. Heti 3-4 koncert nyáron.',
                'rating'        => 4.6,
                'date'          => '2026-11-15',
                'time'          => '19:00:00',
                'location'      => 'Budapest, Fábián Juli tér 1',
                'image_url'     => 'https://i.szalas.hu/pois/5034/original/88300.jpg',
                'category'      => 'Fesztivál',
                'organizer'     => 'Budapest Park',
                'tags'          => 'Concert,Festival,Outdoor',
                'price'         => '5990-19990 Ft',
                'contact_phone' => '+36 1 434 7800',
            ],
            [
                'title'         => 'Balaton Sound Fesztivál',
                'description'   => 'Elektronikus zenei fesztivál Budapesttől 1 órára! Techno, house, trance a Balaton-parton. Kempingezés, strandfesztivál feeling. Nemzetközi DJ-k, 3 színpad. Beach party atmosphere. Vízisportok, napozás. 3 napos zenei ünnep.',
                'rating'        => 4.4,
                'date'          => '2026-12-25',
                'time'          => '18:00:00',
                'location'      => 'Zamárdi, Kiss Ernő utca 44.',
                'image_url'     => 'https://likebalaton.hu/wp-content/uploads/2024/02/9127461marksomay202306282049DJI202306282049510050D-scaled.jpg',
                'category'      => 'Fesztivál',
                'organizer'     => 'B My Lake',
                'tags'          => 'Electronic,Techno,House',
                'price'         => '29990 Ft (3 napos bérlet)',
                'contact_phone' => '+36 1 372 0650',
            ],
            [
                'title'         => 'Party Villa',
                'description'   => 'Exkluzív villa buli a Buda-hegyekben! Medence, jacuzzi, tágas teraszok és panoráma a városra. Profi DJ, minőségi hangrendszer, LED világítás. Korlátozott létszám - max 150 fő. BYOB vagy prémium bárszolgáltatás. Privát biztonságiak. Tökéletes születésnapi, céges vagy baráti bulira. Előzetes regisztráció kötelező!',
                'rating'        => 4.2,
                'date'          => '2026-08-14',
                'time'          => '20:00:00',
                'location'      => 'Budapest, Veres Péter út 121.',
                'image_url'     => 'https://picsum.photos/800/600?random=26',
                'category'      => 'Házibuli',
                'organizer'     => 'Party Villa Budapest',
                'tags'          => 'Villa,Exclusive,Private',
                'price'         => '5000 Ft',
                'contact_phone' => '+36 70 633 7599',
            ],
            [
                'title'         => 'The Private Rooftop',
                'description'   => 'Születésnapi buli egy pentház tetőteraszán! Panoráma kilátás, bubble machine, neon dekor. DJ mix és karaoke. Koktélbár, finger food. Dress code: party outfit. Privát esemény, csak meghívással. Korhatár: 18+',
                'rating'        => 4.3,
                'date'          => '2026-08-20',
                'time'          => '21:00:00',
                'location'      => 'Budapest, Hermina út 63',
                'image_url'     => 'https://picsum.photos/800/600?random=28',
                'category'      => 'Házibuli',
                'organizer'     => 'Privát',
                'tags'          => 'Birthday,Rooftop,Exclusive',
                'price'         => '2000 Ft',
                'contact_phone' => '+36 30 343 6427',
            ],
            [
                'title'         => 'Volt Fesztivál',
                'description'   => 'Magyarország egyik legnagyobb nyári fesztiválja! Rock, pop, elektronikus zene. Nemzetközi és hazai sztárok. 4 nap, több színpad. Kempingezés, glamping opció. Strand a közelben. Sopron, fergeteges hangulat!',
                'rating'        => 4.6,
                'date'          => '2026-12-30',
                'time'          => '15:00:00',
                'location'      => 'Sopron, Szent György utca 2.',
                'image_url'     => 'https://picsum.photos/800/600?random=37',
                'category'      => 'Fesztivál',
                'organizer'     => 'Volt Fesztivál',
                'tags'          => 'Rock,Pop,Electronic',
                'price'         => '69990 Ft (4 napos bérlet)',
                'contact_phone' => '+36 30 951 9750',
            ],
            [
                'title'         => 'Fishing On Orfű',
                'description'   => 'Alternatív indie-rock fesztivál gyönyörű környezetben! Magyar és külföldi indie bandák. Tó, erdő, túrázás. Családbarát, barátságos hangulat. Craft sörök, street food. Hippi vibe. 3 nap.',
                'rating'        => 4.8,
                'date'          => '2026-12-08',
                'time'          => '14:00:00',
                'location'      => 'Orfű, Dollár út 1.',
                'image_url'     => 'https://picsum.photos/800/600?random=39',
                'category'      => 'Fesztivál',
                'organizer'     => 'Fishing On Orfű',
                'tags'          => 'Indie,Rock,Alternative',
                'price'         => '29990 Ft (3 napos bérlet)',
                'contact_phone' => '+36 30 773 6538',
            ],
            [
                'title'         => 'Bálna Terasz',
                'description'   => 'Stílusos duna-parti terasz lounge a Bálnában! Sunset cocktails, chill house music. Elegáns közönség, fingerfood menü. Perfect for networking. Dress code: smart casual. Panoráma a Budai Várra.',
                'rating'        => 4.2,
                'date'          => '2026-07-28',
                'time'          => '18:00:00',
                'location'      => 'Budapest, Bálna Budapest, Fővám tér 11-12',
                'image_url'     => 'https://picsum.photos/800/600?random=40',
                'category'      => 'Egyéb',
                'organizer'     => 'Bálna Budapest',
                'tags'          => 'Lounge,Terrace,Elegant',
                'price'         => '2500 Ft',
                'contact_phone' => '+36 30 410 7123',
            ],
            [
                'title'         => 'Sparty - Széchenyi Bath Party',
                'description'   => 'Exkluzív fürdőbuli! Széchenyi vagy Lukács fürdő after hours. DJ-k, LED fények a vízben. Fürdőruha kötelező! Cocktail bár, chill zónák. Egyedi budapesti élmény turistáknak és helyieknek!',
                'rating'        => 4.6,
                'date'          => '2026-08-21',
                'time'          => '22:00:00',
                'location'      => 'Budapest, Állatkerti krt. 9-11',
                'image_url'     => 'https://picsum.photos/800/600?random=43',
                'category'      => 'Egyéb',
                'organizer'     => 'Sparty Budapest',
                'tags'          => 'Thermal,Bath,Unique',
                'price'         => '20000 Ft (fürdővel)',
                'contact_phone' => '+36 30 395 8581',
            ],
        ];

        foreach ($events as $event) {
            Event::create($event);
        }
    }
}
